"""Output guardrails — validate LLM outputs before using them.

These guardrails sit between LLM responses and downstream consumers
(database execution, user display). They catch unsafe or malformed
outputs that the LLM might produce.

Three types of validation:
1. SQL validation — ensure generated SQL is SELECT-only, no DML/DDL
2. Extraction JSON validation — ensure vision output is valid structured JSON
3. Grounding check — ensure text answer references actual data (no hallucination)
"""

import json
import re
from src.common.schemas import GuardrailResult
from src.common.config_loader import load_settings
from src.common.utils import DML_PATTERN, strip_markdown_fences  # noqa: F401 — strip_markdown_fences available for callers


# ── SQL Validation ───────────────────────────────────────────────────

# Use shared DML pattern from utils to avoid duplication
_DANGEROUS_SQL = DML_PATTERN

# Detects multiple SQL statements separated by semicolons.
# Multi-statement queries are a common SQL injection vector.
_MULTI_STATEMENT = re.compile(r";\s*\w", re.IGNORECASE)


def _get_default_limit() -> int:
    """Load default row limit from config instead of hardcoding."""
    settings = load_settings()
    return settings.get("analytics", {}).get("default_row_limit", 100)


def validate_sql(sql: str) -> GuardrailResult:
    """Validate LLM-generated SQL before database execution.

    Checks (in order):
    1. Non-empty — reject blank SQL
    2. No DML/DDL — block INSERT, UPDATE, DELETE, DROP, etc.
    3. Must start with SELECT — only read operations allowed
    4. No multi-statement — block "SELECT ...; DROP TABLE ..." patterns
    5. Auto-add LIMIT — append LIMIT if the LLM forgot it

    Args:
        sql: The SQL string generated by the LLM.

    Returns:
        GuardrailResult with sanitized_input containing the
        (possibly LIMIT-appended) SQL on success.
    """
    stripped = sql.strip()

    # Block empty SQL
    if not stripped:
        return GuardrailResult(
            passed=False,
            reason="Empty SQL query.",
        )

    # Block DML/DDL operations
    if _DANGEROUS_SQL.match(stripped):
        return GuardrailResult(
            passed=False,
            reason=f"Dangerous SQL operation detected: {stripped[:50]}...",
            blocked_patterns=[_DANGEROUS_SQL.pattern],
        )

    # Must start with SELECT (blocks PRAGMA, ATTACH, EXPLAIN, etc.)
    if not stripped.upper().startswith("SELECT"):
        return GuardrailResult(
            passed=False,
            reason=f"Only SELECT queries are allowed. Got: {stripped[:50]}...",
        )

    # Block multi-statement queries (SQL injection defense)
    # Check for any semicolon followed by non-whitespace-only content.
    # Also check for any semicolon in the middle of the statement (not just trailing).
    # This catches bypass patterns like ";\t\nDROP" that the regex misses.
    if _MULTI_STATEMENT.search(stripped):
        return GuardrailResult(
            passed=False,
            reason="Multi-statement queries are not allowed.",
            blocked_patterns=["multi-statement"],
        )
    stripped_no_trailing = stripped.rstrip(';').rstrip()
    if ';' in stripped_no_trailing:
        return GuardrailResult(
            passed=False,
            reason="Multiple SQL statements detected",
        )

    # Auto-add LIMIT if the LLM forgot to include one (limit from config)
    sanitized = stripped
    if "LIMIT" not in sanitized.upper():
        sanitized = sanitized.rstrip(";").rstrip() + f" LIMIT {_get_default_limit()}"

    return GuardrailResult(
        passed=True,
        sanitized_input=sanitized,
    )


# ── Extraction JSON Validation ───────────────────────────────────────

def validate_extraction_json(raw_response: str) -> GuardrailResult:
    """Validate vision LLM output is valid JSON with the expected structure.

    Expected JSON structure from the vision model:
    {
        "fields": {"field_name": "value", ...},
        "confidence_scores": {"field_name": 0.95, ...},
        "document_type": "invoice",
        "notes": "..."
    }

    Handles common LLM output quirks:
    - Markdown-wrapped JSON (```json ... ```) is stripped
    - Confidence scores outside [0, 1] are clamped (not rejected)

    Args:
        raw_response: Raw string response from the vision LLM.

    Returns:
        GuardrailResult with sanitized_input containing the
        cleaned/validated JSON string on success.
    """
    if not raw_response or not raw_response.strip():
        return GuardrailResult(
            passed=False,
            reason="Empty response from vision model.",
        )

    cleaned = raw_response.strip()

    # Strip markdown code blocks if the LLM wrapped the JSON
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        # Remove opening ```json or ``` line
        if lines[0].startswith("```"):
            lines = lines[1:]
        # Remove closing ``` line
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()

    # Attempt to parse as JSON
    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        return GuardrailResult(
            passed=False,
            reason=f"Invalid JSON: {str(e)[:100]}",
        )

    # Validate top-level structure is a dict
    if not isinstance(data, dict):
        return GuardrailResult(
            passed=False,
            reason="Expected a JSON object, got something else.",
        )

    # Verify required keys are present
    for key in ("fields", "confidence_scores", "document_type"):
        if key not in data:
            return GuardrailResult(
                passed=False,
                reason=f"Missing required key: '{key}'",
            )

    # Clamp confidence scores to valid [0, 1] range instead of rejecting
    if isinstance(data.get("confidence_scores"), dict):
        for field, score in data["confidence_scores"].items():
            if isinstance(score, (int, float)):
                data["confidence_scores"][field] = max(0.0, min(1.0, float(score)))

    return GuardrailResult(
        passed=True,
        sanitized_input=json.dumps(data),
    )


# ── Grounding Check ──────────────────────────────────────────────────

# Phrases in LLM answers that claim data exists. If the SQL returned
# no rows but the LLM uses these phrases, it is hallucinating.
_DATA_CLAIM_PATTERNS = [
    re.compile(r"the data shows", re.IGNORECASE),
    re.compile(r"according to the (results|data|query)", re.IGNORECASE),
    re.compile(r"the (results|query) (show|indicate|reveal)", re.IGNORECASE),
    re.compile(r"there are \d+", re.IGNORECASE),
    re.compile(r"the (total|average|sum|count) is", re.IGNORECASE),
]


def validate_grounding(answer_text: str, sql_result: list[dict]) -> GuardrailResult:
    """Check that the LLM's text answer is grounded in actual query results.

    This is a heuristic anti-hallucination check, not a full fact-verification
    system. It catches the most obvious case: the LLM claiming data exists
    when the query returned zero rows.

    Rules:
    - If sql_result has data: PASS (we trust the LLM used the data)
    - If sql_result is empty and answer claims data exists: FAIL
    - If sql_result is empty and answer acknowledges no data: PASS

    Args:
        answer_text: The LLM-generated natural language answer.
        sql_result: The actual query results (list of row dicts).

    Returns:
        GuardrailResult with passed=True if grounded, False if hallucinating.
    """
    has_data = bool(sql_result) and len(sql_result) > 0

    if has_data:
        # Data exists — answer is assumed grounded
        return GuardrailResult(passed=True)

    # No data returned — check if the answer falsely claims data exists
    for pattern in _DATA_CLAIM_PATTERNS:
        if pattern.search(answer_text):
            return GuardrailResult(
                passed=False,
                reason="Answer claims data exists but query returned no results.",
                blocked_patterns=[pattern.pattern],
            )

    # No data, and answer does not claim data — acceptable
    return GuardrailResult(passed=True)
